/*
 * apex_board.h
 *
 * Board-level helpers, and the one header the rest of the project can
 * include to reach everything.
 *
 * WHERE THE PIN NAMES COME FROM
 *
 *   The _Pin and _GPIO_Port macros used below are generated by CubeMX
 *   into Core/Inc/main.h, from the User Labels set on each pin in the
 *   .ioc file. Nothing here hard-codes a pin number, so the .ioc remains
 *   the single source of truth for the pin map: change a label there,
 *   regenerate, and this follows automatically.
 *
 * WHY THE POLARITY HELPERS EXIST
 *
 *   Two signals on this board are ACTIVE LOW -- the pin must be driven
 *   low to make the thing happen. Every caller that had to remember
 *   which ones would eventually get one wrong, so the polarity is
 *   written down once, here, and nothing else is allowed to know it.
 *
 * THE FOLDER LAYOUT
 *
 *     board/     this file, and the unit conventions
 *     drivers/   the peripherals: encoder, bridge, sensors, USB
 *     comms/     framing, protocols, and the command handlers
 *     control/   the control loop and what runs inside it
 *     motion/    things that drive the motor: spin, calibrate, measure
 *     monitor/   telemetry and the protection supervisor
 */

#ifndef APEX_BOARD_H_
#define APEX_BOARD_H_

#include "main.h"

/* Aggregate include, so a source file needs only this one header.
 * Ordered by layer, lowest first. */
#include "units.h"

#include "USB_Comm.h"
#include "encoder.h"
#include "gate_driver.h"
#include "sensors.h"

#include "motor.h"
#include "control.h"

#include "cobs.h"
#include "crc16.h"
#include "packet.h"
#include "protocol.h"
#include "protocol_text.h"
#include "protocol_binary.h"
#include "commands.h"

#include "openloop.h"
#include "calibration.h"
#include "estimate.h"

#include "telemetry.h"
#include "protection.h"

/* ------------------------------------------------------------------
 * Status LEDs
 *
 * Both ACTIVE HIGH: each LED has its cathode to ground and its anode to
 * the pin through a 5.1k resistor, so driving the pin high lights it.
 *
 *   LED1 = PB7, schematic net "status"
 *   LED2 = PB8, schematic net "comError"
 * ------------------------------------------------------------------ */

/**
 * Set the status LED.
 *
 * @param on  non-zero to light it, zero to extinguish it
 */
static inline void led1(uint8_t on)
{
    HAL_GPIO_WritePin(LED1_GPIO_Port, LED1_Pin,
                      (on != 0u) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/**
 * Set the error LED.
 *
 * @param on  non-zero to light it, zero to extinguish it
 */
static inline void led2(uint8_t on)
{
    HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin,
                      (on != 0u) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/**
 * Invert the status LED. Used for the heartbeat, where only the change
 * matters and not the resulting state.
 */
static inline void led1_toggle(void)
{
    HAL_GPIO_TogglePin(LED1_GPIO_Port, LED1_Pin);
}

/**
 * Invert the error LED.
 */
static inline void led2_toggle(void)
{
    HAL_GPIO_TogglePin(LED2_GPIO_Port, LED2_Pin);
}

/* ------------------------------------------------------------------
 * RS-485 direction
 *
 * The transceiver's driver-enable and receiver-enable pins are tied
 * together on this board, so one line selects the direction of the
 * whole part. Receiver-enable is active low and driver-enable active
 * high, which is exactly why tying them works: one level transmits, the
 * other receives, and neither leaves both active at once.
 * ------------------------------------------------------------------ */

/**
 * Choose the RS-485 direction.
 *
 * @param transmit  non-zero to drive the bus, which drives the pin HIGH;
 *                  zero to listen, driving it LOW
 */
static inline void rs485_set_transmit(uint8_t transmit)
{
    HAL_GPIO_WritePin(RS485EN_GPIO_Port, RS485EN_Pin,
                      (transmit != 0u) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

#endif /* APEX_BOARD_H_ */
